# Generated by Django 4.2.4 on 2023-08-22 06:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=7, unique=True)),
                ('make', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=16)),
                ('yom', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2099)])),
                ('logbook', models.TextField(blank=True, null=True)),
                ('chasis_no', models.CharField(blank=True, max_length=32, null=True)),
                ('engine_no', models.CharField(blank=True, max_length=32, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.partner')),
            ],
        ),
    ]
