# Generated by Django 4.2.4 on 2023-08-22 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0005_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=255)),
                ('issue_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Valid', max_length=16)),
                ('document', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.insurer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.vehicle')),
            ],
        ),
    ]
