# Generated by Django 4.2.4 on 2023-08-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0006_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UberInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('document', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='NtsaInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_number', models.CharField(max_length=7, unique=True)),
                ('booking_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('document', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.vehicle')),
            ],
        ),
    ]
