# Generated by Django 4.2.4 on 2023-08-22 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0007_uberinspection_ntsainspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=8, unique=True)),
                ('license_status', models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Valid', max_length=32)),
                ('psv_status', models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid')], default='Valid', max_length=16)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.driver')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField()),
                ('document', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('driverlicense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.driverlicense')),
            ],
        ),
    ]
