# Generated by Django 4.2.4 on 2023-08-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0008_driverlicense_licenserenewal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsvRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField()),
                ('document', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('driverlicense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.driverlicense')),
            ],
        ),
    ]
