# Generated by Django 4.2.4 on 2023-08-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0009_psvrenewal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('document', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('performing', 'Performing'), ('substandard', 'Substandard'), ('active', 'Active'), ('off', 'Off'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.vehicle')),
            ],
        ),
    ]
