# Generated by Django 4.2.4 on 2023-08-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0010_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_amount', models.PositiveSmallIntegerField(default=0)),
                ('weekly_run', models.CharField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default='4', max_length=16)),
                ('mileage_based', models.BooleanField(default=True)),
                ('price_per_km', models.PositiveSmallIntegerField(default=0)),
                ('weeks', models.PositiveSmallIntegerField(default=0)),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('delayed', 'Delayed'), ('defaulted', 'Defaulted'), ('hold', 'Hold')], default='active', max_length=16)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('paid_amount', models.PositiveIntegerField(default=0)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('mileage', models.PositiveIntegerField(default=0)),
                ('issue_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partial'), ('default', 'Default')], default='unpaid', max_length=16)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.account')),
            ],
        ),
    ]
