# Generated by Django 4.2.4 on 2023-08-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0011_account_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.CharField(max_length=16)),
                ('transaction_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('split', models.BooleanField(default=False)),
                ('index', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('split_amount', models.PositiveIntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.invoice')),
            ],
        ),
    ]
