# Generated by Django 4.2.4 on 2023-08-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0012_mobilepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('msisdn', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=16)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('maintenace_type', models.CharField(choices=[('routine', 'Routine'), ('adhoc', 'Adhoc'), ('post_accident', 'Post Accident')], default='routine', max_length=16)),
                ('maintenance_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.contract')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.maintenanceprovider')),
            ],
        ),
    ]
