# Generated by Django 4.2.4 on 2023-08-22 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0013_maintenanceprovider_vehiclemaintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('sparepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.sparepart')),
                ('vehiclemaintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.vehiclemaintenance')),
            ],
        ),
    ]
