# Generated by Django 4.2.4 on 2023-08-22 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0014_sparepart_maintenancepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('platform', models.CharField(choices=[('protrack', 'ProTrackGPS'), ('whatsgps', 'WhatsGPS')], default='protrack', max_length=16)),
                ('access_token', models.CharField(default='Test', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TransactionType', models.CharField(max_length=64)),
                ('TransID', models.CharField(max_length=50, unique=True)),
                ('TransAmount', models.IntegerField()),
                ('MSISDN', models.BigIntegerField()),
                ('FirstName', models.CharField(max_length=200)),
                ('MiddleName', models.CharField(blank=True, max_length=200, null=True)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('BillRefNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('TransTime', models.CharField(blank=True, max_length=200, null=True)),
                ('Reconciled', models.BooleanField(default=False)),
                ('ReconciledCounter', models.IntegerField(default=0)),
                ('Unallocated', models.IntegerField(default=0)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('UpdateDate', models.DateTimeField(auto_now=True)),
                ('Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uwezo_api.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='tracker',
            name='accesstoken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uwezo_api.accesstoken'),
        ),
    ]
