# Generated by Django 4.2.4 on 2023-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0016_vehiclemake_vehiclemodel_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='claim_form',
            field=models.FileField(blank=True, upload_to='claim_forms/'),
        ),
    ]
