# Generated by Django 4.2.4 on 2023-08-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0017_alter_insurer_claim_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='claim_form',
            field=models.TextField(blank=True),
        ),
    ]
