# Generated by Django 4.2.4 on 2023-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0018_alter_insurer_claim_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='id_document',
            field=models.FileField(blank=True, help_text='Upload an ID document (PDF or image, max 5MB)', null=True, upload_to='id_documents/'),
        ),
    ]
