# Generated by Django 4.2.4 on 2023-09-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0023_alter_mobilepayment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id_document',
        ),
        migrations.AlterField(
            model_name='driver',
            name='document_type',
            field=models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('military_id', 'Military ID')], default='national_id', max_length=16),
        ),
        migrations.AlterField(
            model_name='partner',
            name='document_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('military_id', 'Military ID')], default='national_id', max_length=16, null=True),
        ),
    ]
