# Generated by Django 4.2.4 on 2023-09-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0024_remove_driver_id_document_alter_driver_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='msisdn',
            field=models.PositiveIntegerField(help_text='Kenyan mobile number in the format +254XXXXXXXXX', max_length=15, unique=True),
        ),
    ]
