# Generated by Django 4.2.4 on 2023-09-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0025_alter_partner_msisdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='msisdn',
            field=models.PositiveBigIntegerField(help_text='Kenyan mobile number in the format +254XXXXXXXXX'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='msisdn',
            field=models.PositiveBigIntegerField(help_text='Kenyan mobile number in the format +254XXXXXXXXX'),
        ),
    ]
