# Generated by Django 4.2.6 on 2023-10-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uwezo_api', '0026_alter_driver_msisdn_alter_partner_msisdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='document_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('military_id', 'Military ID')], default='national_id', max_length=32, null=True),
        ),
    ]
